/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.udesc.argc.gui.view;

/**
 *
 * @author gabrielnaoto
 */
public class Window extends javax.swing.JFrame {

    /**
     * Creates new form Application
     */
    public Window() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        itemConfiguracoes = new javax.swing.JMenu();
        configurarFeed = new javax.swing.JMenuItem();
        configurarTermos = new javax.swing.JMenuItem();
        configurarHorarios = new javax.swing.JMenuItem();
        itemFeed = new javax.swing.JMenu();
        consultarNoticias = new javax.swing.JMenuItem();
        executarVerificacao = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RSS Manager");
        setFocusableWindowState(false);

        itemConfiguracoes.setText("Manage");

        configurarFeed.setText("Manage feeds");
        itemConfiguracoes.add(configurarFeed);

        configurarTermos.setText("Manage subjects");
        itemConfiguracoes.add(configurarTermos);

        configurarHorarios.setText("Manage schedules");
        itemConfiguracoes.add(configurarHorarios);

        jMenuBar1.add(itemConfiguracoes);

        itemFeed.setText("RSS feed");

        consultarNoticias.setText("News found");
        itemFeed.add(consultarNoticias);

        executarVerificacao.setText("Run checks (not scheduled)");
        itemFeed.add(executarVerificacao);

        jMenuBar1.add(itemFeed);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuItem configurarFeed;
    public javax.swing.JMenuItem configurarHorarios;
    public javax.swing.JMenuItem configurarTermos;
    public javax.swing.JMenuItem consultarNoticias;
    public javax.swing.JMenuItem executarVerificacao;
    private javax.swing.JMenu itemConfiguracoes;
    private javax.swing.JMenu itemFeed;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
